#!/usr/bin/env bash
#
# Orbis Naro Global Installation Script
#
# This script installs naro globally so it can be used from anywhere.
# It creates symlinks or copies the naro executable to a directory in PATH.
#
# Usage:
#   ./install.sh                    # Install to ~/.local/bin (recommended)
#   ./install.sh --system           # Install to /usr/local/bin (requires sudo)
#   ./install.sh --path /custom/bin # Install to custom path
#   ./install.sh --uninstall        # Remove global installation
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_error() {
    echo -e "${RED}❌ $1${NC}" >&2
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_header() {
    echo -e "${BLUE}=== $1 ===${NC}"
}

# Default installation directory
DEFAULT_INSTALL_DIR="$HOME/.local/bin"
INSTALL_DIR=""
SYSTEM_INSTALL=false
UNINSTALL=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --system)
            SYSTEM_INSTALL=true
            INSTALL_DIR="/usr/local/bin"
            shift
            ;;
        --path)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --uninstall)
            UNINSTALL=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo "Install Orbis Naro globally so it can be used from anywhere."
            echo ""
            echo "Options:"
            echo "  --system          Install to /usr/local/bin (requires sudo)"
            echo "  --path PATH       Install to custom directory"
            echo "  --uninstall       Remove global installation"
            echo "  -h, --help        Show this help message"
            echo ""
            echo "Default: Installs to ~/.local/bin"
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Set default install directory if not specified
if [[ -z "$INSTALL_DIR" ]]; then
    INSTALL_DIR="$DEFAULT_INSTALL_DIR"
fi

# Uninstall function
uninstall_naro() {
    print_header "Uninstalling Orbis Naro"
    
    local removed=false
    
    # Check common installation locations
    local locations=(
        "$HOME/.local/bin/naro"
        "/usr/local/bin/naro"
        "$INSTALL_DIR/naro"
    )
    
    for location in "${locations[@]}"; do
        if [[ -f "$location" ]] || [[ -L "$location" ]]; then
            print_info "Removing $location..."
            rm -f "$location"
            removed=true
        fi
    done
    
    if [[ "$removed" == "true" ]]; then
        print_success "Orbis Naro uninstalled successfully"
    else
        print_warning "No global naro installation found"
    fi
    
    exit 0
}

# Check if running uninstall
if [[ "$UNINSTALL" == "true" ]]; then
    uninstall_naro
fi

# Install function
install_naro() {
    print_header "Installing Orbis Naro Globally"
    
    print_info "Project root: $PROJECT_ROOT"
    print_info "Install directory: $INSTALL_DIR"
    
    # Verify project structure
    if [[ ! -f "$PROJECT_ROOT/dev/naro/naro" ]]; then
        print_error "Naro script not found at $PROJECT_ROOT/dev/naro/naro"
        print_error "Looking for naro at project root..."
        if [[ ! -f "$PROJECT_ROOT/naro" ]]; then
            print_error "Naro script not found at $PROJECT_ROOT/naro either"
            print_error "Make sure you're running this from within the Orbis project"
            exit 1
        else
            print_info "Found naro script at project root: $PROJECT_ROOT/naro"
        fi
    fi
    
    # Create install directory if it doesn't exist
    if [[ ! -d "$INSTALL_DIR" ]]; then
        print_info "Creating install directory: $INSTALL_DIR"
        mkdir -p "$INSTALL_DIR"
    fi
    
    # Check if we need sudo for system installation
    if [[ "$SYSTEM_INSTALL" == "true" ]] && [[ ! -w "$INSTALL_DIR" ]]; then
        print_warning "System installation requires sudo privileges"
        SUDO_CMD="sudo"
    else
        SUDO_CMD=""
    fi
    
    # Create the global naro wrapper script
    local global_script="$INSTALL_DIR/naro"
    
    print_info "Creating global naro wrapper..."
    
    # Write the global wrapper script
    $SUDO_CMD tee "$global_script" > /dev/null << EOF
#!/usr/bin/env bash
#
# Orbis Naro Global Wrapper
#
# This script allows running naro from anywhere by finding the Orbis project
# and executing the appropriate naro script.
#
# Auto-generated by: $0
# Project root: $PROJECT_ROOT
#

set -e

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

print_error() {
    echo -e "\${RED}❌ \$1\${NC}" >&2
}

print_info() {
    echo -e "\${BLUE}ℹ️  \$1\${NC}"
}

# Function to find Orbis project root
find_orbis_project() {
    local current_dir="\$(pwd)"
    
    while [[ "\$current_dir" != "/" ]]; do
        # Check for Orbis project indicators
        if [[ -f "\$current_dir/pyproject.toml" ]] && \\
           [[ -d "\$current_dir/orbis-core" ]] && \\
           [[ -d "\$current_dir/providers" ]] && \\
           [[ -d "\$current_dir/dev/naro" ]]; then
            echo "\$current_dir"
            return 0
        fi
        current_dir="\$(dirname "\$current_dir")"
    done
    
    # If not found in current path, try the original installation location
    if [[ -f "$PROJECT_ROOT/dev/naro/naro" ]]; then
        echo "$PROJECT_ROOT"
        return 0
    fi
    
    return 1
}

# Find the Orbis project
if PROJECT_ROOT=\$(find_orbis_project); then
    # First try the main naro script at project root
    if [[ -f "\$PROJECT_ROOT/naro" ]]; then
        NARO_SCRIPT="\$PROJECT_ROOT/naro"
    elif [[ -f "\$PROJECT_ROOT/dev/naro/naro" ]]; then
        NARO_SCRIPT="\$PROJECT_ROOT/dev/naro/naro"
    else
        print_error "Naro script not found in project"
        exit 1
    fi
else
    print_error "Orbis project not found"
    print_info "Please run this command from within an Orbis project directory"
    print_info "Or ensure the original project is still at: $PROJECT_ROOT"
    exit 1
fi

# Execute the naro script
exec "\$NARO_SCRIPT" "\$@"
EOF

    # Make the script executable
    $SUDO_CMD chmod +x "$global_script"
    
    print_success "Naro installed globally at: $global_script"
    
    # Check if install directory is in PATH
    if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
        print_warning "⚠️  $INSTALL_DIR is not in your PATH"
        print_info "Add the following line to your shell configuration file:"
        echo ""
        echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
        echo ""
        print_info "Then restart your shell or run: source ~/.bashrc (or ~/.zshrc)"
    else
        print_success "✅ $INSTALL_DIR is already in your PATH"
        print_info "You can now run 'naro' from anywhere!"
    fi
    
    # Test the installation
    print_info "Testing installation..."
    if "$global_script" --help > /dev/null 2>&1; then
        print_success "Installation test passed!"
    else
        print_warning "Installation test failed - you may need to adjust your setup"
    fi
}

# Run the installation
install_naro